#pragma once
#include "../memUtils.hpp"

#ifdef __arm__
#define OFFSET_MAGICIAN_IMMUNE 0x87A9E4
#define OFFSET_HEALER_IMMUNE 0x877AC4
#define OFFSET_MAGICIAN_CONDITION 0x8628B0
#define OFFSET_HEALER_CONDITION 0x8446A8
#define OFFSET_HEALER_INITIALIZE_FAMILY_IMMUNITIES 0x8628C4
#define Z_FAMILY_FUNC_ADDR 0x8BD2C0

#elif __aarch64__
#define OFFSET_MAGICIAN_IMMUNE 0xC12B7C
#define OFFSET_HEALER_IMMUNE 0xC0F91C
#define OFFSET_MAGICIAN_CONDITION 0xBF7A78
#define OFFSET_HEALER_CONDITION 0xBD8578
#define OFFSET_HEALER_INITIALIZE_FAMILY_IMMUNITIES 0xBF7BEC
#define Z_FAMILY_FUNC_ADDR 0xC5677C

#endif

class ImmunityMgr
{
public:
	static void ImmunityRemovalHook();
};